linters-settings:
  decorder:
    disable-dec-num-check: true
    disable-dec-order-check: false
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  goimports:
    local-prefixes: github.com/ayoisaiah/stellar-photos
  gomnd:
    checks:
      - argument
      - case
      - condition
      - return
  govet:
    check-shadowing: true
    enable-all: true
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: error-naming
        severity: warning
        disabled: true # handled by errname

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - decorder
    - errcheck
    - errorlint
    - errname
    - exportloopref
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - godot
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - mirror
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - perfsprint
    - revive
    - staticcheck
    - stylecheck
    - sloglint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

issues:
  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  issues-exit-code: 1
  allow-parallel-runners: true
