services:
  app:
    image: stellar-photos:1.0.0-alpine
    build:
      context: .
      target: final
    container_name: stellar-photos
    volumes:
      - .:/stellar-photos
    restart: unless-stopped
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost:8080']
      interval: 1m
      timeout: 10s
      retries: 5
    logging:
      driver: local
    expose:
      - '8080'

  webserver:
    image: caddy:2.9.1-alpine
    container_name: caddy
    depends_on:
      - app
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - '80:80'
      - '443:443'
      - '2019:2019'
    restart: unless-stopped
    logging:
      driver: local

networks:
  default:
    name: stellar-photos
    driver: bridge

volumes:
  caddy-config:
  caddy-data:


