name: Run tests, build server Docker image, and deploy to production
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '!server/**'

    branches:
      - master

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      # Tests
      - name: Run testing
        run: go test ./... -race

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          # prettier-ignore
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
      - name: Create SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          envkey_ONEDRIVE_APPID: ${{ secrets.ONEDRIVE_APPID }}
          envkey_ONEDRIVE_SECRET: ${{ secrets.ONEDRIVE_SECRET }}
          envkey_GOOGLE_DRIVE_KEY: ${{ secrets.GOOGLE_DRIVE_KEY }}
          envkey_GOOGLE_DRIVE_SECRET: ${{ secrets.GOOGLE_DRIVE_SECRET }}
          envkey_DROPBOX_KEY: ${{ secrets.DROPBOX_KEY }}
          envkey_REDIRECT_URL: ${{ secrets.REDIRECT_URL }}
          envkey_LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          envkey_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          envkey_TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          directory: ./server/scripts

      - name: Copy files to server via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          local: './server/scripts'
          remote: 'stellar_github_action'
          dotfiles: true

      - name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # prettier-ignore
          script: chmod +x stellar_github_action/deploy.sh && ./stellar_github_action/deploy.sh
