name: Tests

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    # Tests
    - name: Run testing
      run: go test ./... -race
      env:
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        ONEDRIVE_APPID: ${{ secrets.ONEDRIVE_APPID }}
        ONEDRIVE_SECRET: ${{ secrets.ONEDRIVE_SECRET }}
        GOOGLE_DRIVE_KEY: ${{ secrets.GOOGLE_DRIVE_KEY }}
        GOOGLE_DRIVE_SECRET: ${{ secrets.GOOGLE_DRIVE_SECRET }}
        REDIRECT_URL: ${{ secrets.REDIRECT_URL }}
        DROPBOX_KEY: ${{ secrets.DROPBOX_KEY }}
